### ISSUE TITLE
[W4-geospatial-data-project] Cristian Castro Blua

### ISSUE THREAD

**Issue by ccastroblua** [Ironhack-Data-Madrid-Mayo-2021/W4-geospatial-data-project#1]
https://github.com/ccastroblua/geospatial_project

**Comment by olmocorell** [comment]
¡¡Hola Cristian!!
Te cuento cositas del proyecto

### Readme
Nada que decir, está espectacular.
Solamente en la parte del stack de tecnologías decirte que en markdown puedes incluir los enlaces en el texto si lo escribes `[así](aquíelenlace)` y así la palabra que se refiera a la tecnología se puede pinchar sobre ella.
Quedaría así: [Pandas](https://pandas.pydata.org/)

### Code/Repository structure
[Aquí](https://github.com/ccastroblua/geospatial_project/blob/main/mongo_and_cleaning.ipynb) ten cuidado cuando hagas una query que devuelve muchos documentos a la hora de printearla en jupyter que luego en github se ve infinito y no se encuentra el código.

### Code efficiency / Code syntax (conventions)
[Aquí](https://github.com/ccastroblua/geospatial_project/blob/main/src/functions.py) tienes una función de 150 líneas... a ver, no es que por definición esté mal hacer una función tan larga, pero nuestro objetivo a la hora de escribir funciones es que sean funciones de propósito único...que estén parametrizadas y que podamos reutilizarlas. En este caso, de esa gran función estoy segura de que podríamos sacar diferentes funciones con diferentes scopes y que esa función vaya llamando a unas u a otras en función de lo que necesite hacer.

Está genial la aproximación que has hecho al proyecto, la ponderación para elegir la oficina, que hayas utilizado las geooqueries y Mongo como motor para tomar las decisiones en base a los datos y que hayas utilizado el pintar mapas como apoyo y no como elemento para tomar esa decisión.


### Improvements
- Stack del readme
- Modularización de funciones
- Prints infinitos


Es un grandísimo trabajo Cristian, por aquí parece que solo pongo "pegas" pero básicamente lo que busco es que proyecto a proyecto os hagáis más grandes.
Enhorabuena por el trabajo que estás haciendo durante el bootcamp, tu participación y tu actitud no solo de trabajo si no de colaboración.

¡¡Seguimos!!


![project](https://user-images.githubusercontent.com/57899051/124637918-a204aa80-de8a-11eb-9585-58a7809d6638.png)
