### ISSUE TITLE
[ W4-geospatial-data-project] - Alvaro Garcia Blazquez

### ISSUE THREAD

**Issue by alvarogb1919** [Ironhack-Data-Madrid-Mayo-2021/W4-geospatial-data-project#2]
Buenas! el link es: https://github.com/alvarogb1919/Geospatial-data-project.-New-office-location
Me falta ajustar un tema de los colores de los markers en el mapa

**Comment by olmocorell** [comment]
¡¡Hola Álvaroooooo!!
Te cuento cosinas del proyecto 🙃 
### Readme
A ver, está increíble...así que no tengo mucho que decir.
Solamente en la parte del stack de tecnologías decirte que en markdown puedes incluir los enlaces en el texto si lo escribes `[así](aquíelenlace)` y así la palabra que se refiera a la tecnología se puede pinchar sobre ella.
Quedaría así: [Pandas](https://pandas.pydata.org/)

### Code/Repository structure
En este sentido... un par de cositas:
Aunque no sea obligatorio o requisito del readme el tema de las funciones.... hacemos archivo de funciones y las metemos ahí, todas parametrizadas y ordenamos el repo ¿vale?

También puedes dividir el trabajo en varios jupyter, y que cada uno esté destinado a un scope del proyecto.

Ojo por otra parte con los print inifnitos ¿Vale? que donde en jupyter hay un scroll, en github no lo hay..... y es difícil encontrar el código. Echa un vistazo [aquí](https://nbviewer.jupyter.org/github/alvarogb1919/Geospatial-data-project.-New-office-location/blob/main/Office%20location%20analysis-Amsterdam.ipynb)


### Code efficiency / Code syntax (conventions)
Cada vez que escribes una línea de código que has escrito antes o que has escrito muy similar, ahí puedes hacer unaa afunción... puedes hacer funciones que hagana queries, requests.... que extraigan información de un json...
Es decir, el paso de hacerlo todo lo tienes, te falta pasar al siiguiente nivel: la automatización.

### Improvements

- Atomización del código
- Diversificación de jupyter (dividir por scopes)
- El pequeñito tema del readme

Por otro lado, y perdona que parece que solo vengo a poner pegas, pero todo lo que os digo es para que mejoréis y sigáis creciendo. Valoro muchísimo el trabajo que has hecho, el proceso, la aproximación, el código, la técnica de las apis y las queries de mongo están genial. Solo queda que le des unas vueltas a lo que te he dicho para dejarlo redondo.
¡¡¡Buen trabajo!!!!



![project](https://user-images.githubusercontent.com/57899051/124641968-8fd93b00-de8f-11eb-80ba-fee4092443a0.png)
