### ISSUE TITLE
[w4-geopastial-data-project]-Olaya Marqués Gómez

### ISSUE THREAD

**Issue by olaya-marques** [Ironhack-Data-Madrid-Mayo-2021/W4-geospatial-data-project#3]
https://github.com/olaya-marques/w4-geopastial-data-project

**Comment by sheriffff** [comment]
Ya te dí extenso feedback en clase. En general, fenomenal. Por sacar algún aprendizaje, te recuerdo mis 2 tips principales.
 - Ten claro cuánto tiempo tienes para contar tu historia. Si tienes, no corras. Tienes un proyect súper bueno cómo para contármelo tan rápido.
 - Al programar, debemos pensar en automatizar. Y había un pelín de manualidades en tu proceso de elección de la ofi óptima.

Felicidades.
