### ISSUE TITLE
[W4-geospatial-data-project] - Victoria-Ruiz-Gallardón

### ISSUE THREAD

**Issue by Vicrgallardon** [Ironhack-Data-Madrid-Mayo-2021/W4-geospatial-data-project#4]
https://github.com/Vicrgallardon/GeoSpatial-Data-Project.git

**Comment by sheriffff** [comment]
No hay README :(
Estructura un poco pobre Vic:
 - No hay carpeta `src`
 - No hay archivo de funciones con código modularizado.
 - No hay resultados en mapa.
 - No hay elección de oficina.

Muy bien estructurado el notebook con títulos para cada cosa, se agradece.

Me da la sensación de que no has subido todo el código. Si es así, nos lo dices por Slack.
